name: Build & SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_ORG: nikitamikhaylovv
      SONAR_TOKEN1: ${{ secrets.SONAR_TOKEN1 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4



      - name: Build lab_4
        run: |
          rm -rf lab_4/build
          mkdir lab_4/build
          cmake -S lab_4 -B lab_4/build 
          build-wrapper-linux-x86-64 --out-dir lab_4/build_wrapper cmake --build lab_4/build --config Release

      - name: SonarCloud scan lab_4
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
        with:
          args: >
            -Dsonar.projectKey=lab_4
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=lab_4
            -Dsonar.cfamily.compile-commands=lab_4/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true